---
- set_fact: manipulate="&"
  when: op=='start'
- set_fact: manipulate="--stop"
  when: op=='stop'

- name: "{{op}} {{service}}"
  shell: "HADOOP_USER_NAME=hive/{{inventory_hostname}}@CLOUD.LOCAL nohup {{home}}/bin/hive --service {{service}} {{manipulate}}"
