- name: Upload shared config files
  copy: src={{ item }} dest="{{ dest }}/conf" mode=644
  with_fileglob:
    - "{{ role_path }}/../shared/keys/hadoop.keytab"

- name: Upload config files
  copy: src={{ item }} dest="{{ dest }}/conf" mode=644
  with_fileglob:
    - "{{ src }}/*"
