- name: Upload shared config files
  copy: src={{ item }} dest="{{ home }}/etc/hadoop" owner="{{ user }}" mode=644
  with_fileglob:
    - "{{role_path}}/../shared/hdfs/*"
    - "{{role_path}}/../shared/keys/*.jks"
    - "{{role_path}}/../shared/keys/*.keytab"
    - "{{role_path}}/../shared/keys/*.secret"
    - "{{ src }}/*"

- file: path="{{ home }}/etc/hadoop/hadoop.keytab" mode=0640
