---
- name: Re-config name node
  vars:
    user: hdfs
    dest: /opt/hdfs/default
    src: "/home/ansible@cloud.local/ansible/hdfs"

  hosts: namenode
  become_user: "{{ user }}"
  become: true

  tags: nn
  tasks:
    - name: Upload config files
      copy: src={{ item }} dest="{{ dest }}/etc/hadoop" owner="{{ user }}" mode=644
      with_fileglob:
        - "{{ src }}/*"

    - file: path="{{ dest }}/etc/hadoop/rack_awareness.sh" mode=0750

- name: Re-config data node
  vars:
    user: hdfs
    dest: /opt/hdfs/default
    src: "/home/ansible@cloud.local/ansible/hdfs"

  hosts: datanode
  become_user: "{{ user }}"
  become: true

  tags: dn
  tasks:
    - name: Upload config files
      copy: src={{ item }} dest="{{ dest }}/etc/hadoop" owner="{{ user }}" mode=644
      with_fileglob:
        - "{{ src }}/*"

    - file: path="{{ dest }}/etc/hadoop/rack_awareness.sh" mode=0750

- name: Re-config data node
  vars:
    user: hdfs
    dest: /opt/hdfs/default
    src: "/home/ansible@cloud.local/ansible/hdfs"

  hosts: journalnode
  become_user: "{{ user }}"
  become: true

  tags: jn
  tasks:
    - name: Upload config files
      copy: src={{ item }} dest="{{ dest }}/etc/hadoop" owner="{{ user }}" mode=644
      with_fileglob:
        - "{{ src }}/*"

    - file: path="{{ dest }}/etc/hadoop/rack_awareness.sh" mode=0750

- name: Re-config Zookeeper
  vars:
    user: root
    dest: /etc/zookeeper
    src: "/home/ansible@cloud.local/ansible/zookeeper"

  hosts: zookeeper
  become_user: "{{ user }}"
  become: true

  tags: zookeeper
  tasks:
    - name: Upload config files
      copy: src={{ item }} dest="{{ dest }}/conf" owner="{{ user }}" mode=644
      with_fileglob:
        - "{{ src }}/*"

