---
- name: Zookeeper Management Script
  hosts: zookeeper
  become: true
  tags: zookeeper

  tasks:
  - name: "{{op}} Zookeeper"
    shell: "systemctl {{op}} zookeeper"
    when: not(op | trim == 'status')

  - name: Status Zookeeper
    shell: "journalctl -u zookeeper --no-page | tail -n 25"
    when: (op | trim == 'status')
    register: status

  - debug: var=status.stdout_lines
  - debug: var=status.stderr_lines

- name: Journal node management
  hosts: journalnode
  become_user: hdfs
  become: true
  tags: journalnode

  vars:
    home: /opt/hdfs/default
    data_folder: /var/hdfs/data

  tasks:
  - name: "{{op}} Journal Nodes"
    shell: "{{home}}/sbin/hadoop-daemon.sh {{op}} journalnode"
    when: (op != 'status')

  - name: Status of Journal Nodes
    shell: "tail -n 25 {{data_folder}}/logs/hadoop-hdfs-journalnode-{{inventory_hostname}}.log"
    register: status

  - debug: var=status.stdout_lines
  - debug: var=status.stderr_lines

