---
- name: HDFS Management Script
  hosts: zookeeper
  become: true
  tags: zookeeper

  tasks:
  - name: "{{op}} Zookeeper"
    shell: "systemctl {{op}} zookeeper"
    when: not(op | trim == 'status')

  - name: Status Zookeeper
    shell: "journalctl -u zookeeper --no-page | tail -n 25"
    when: (op | trim == 'status')
    register: status

  - debug: var=status.stdout_lines
  - debug: var=status.stderr_lines


- name: Journal node management
  hosts: journalnode
  become_user: hdfs
  become: true
  tags: journalnode

  vars:
    home: /opt/hdfs/default
    data_folder: /var/hdfs/data

  tasks:
  - name: "{{op}} Journal Nodes"
    shell: "{{home}}/sbin/hadoop-daemon.sh {{op}} journalnode"

  - name: Status of Journal Nodes
    shell: "tail -n 25 {{data_folder}}/logs/hadoop-hdfs-journalnode-{{inventory_hostname}}.log"
    register: status

  - debug: var=status.stdout_lines
  - debug: var=status.stderr_lines


- name: ZKFC management
  hosts: namenode
  become_user: hdfs
  become: true
  tags: zkfc

  vars:
    home: /opt/hdfs/default
    data_folder: /var/hdfs/data

  tasks:
  - name: "{{op}} ZKFC"
    shell: "{{home}}/sbin/hadoop-daemon.sh {{op}} zkfc"

  - name: Status of Journal Nodes
    shell: "tail -n 25 {{data_folder}}/logs/hadoop-hdfs-zkfc-{{inventory_hostname}}.log"
    register: status

  - debug: var=status.stdout_lines
  - debug: var=status.stderr_lines


- name: Namenode management
  vars:
    servicename: namenode
    home: /opt/hdfs/default
    kerberos_user: nn
    data_folder: /var/hdfs/data

  hosts: "{{servicename}}"
  become_user: hdfs
  become: true
  tags: "{{servicename}}"

  tasks:
  - name: "{{op}} {{servicename}}"
    shell: "HADOOP_USER_NAME={{kerberos_user}}/{{inventory_hostname}}@CLOUD.LOCAL {{home}}/sbin/hadoop-daemon.sh {{op}} {{servicename}}"

  - name: Status of Journal Nodes
    shell: "tail -n 25 {{data_folder}}/logs/hadoop-hdfs-{{servicename}}-{{inventory_hostname}}.log"
    register: status

  - debug: var=status.stdout_lines
  - debug: var=status.stderr_lines


- name: Datanode management
  vars:
    servicename: datanode
    kerberos_user: dn
    home: /opt/hdfs/default
    data_folder: /var/hdfs/data

  hosts: "{{servicename}}"
  become_user: hdfs
  become: true
  tags: "{{servicename}}"

  tasks:
  - name: "{{op}} {{servicename}}"
    shell: "HADOOP_USER_NAME={{kerberos_user}}/{{inventory_hostname}}@CLOUD.LOCAL {{home}}/sbin/hadoop-daemon.sh {{op}} {{servicename}}"

  - name: Status of Journal Nodes
    shell: "tail -n 25 {{data_folder}}/logs/hadoop-hdfs-{{servicename}}-{{inventory_hostname}}.log"
    register: status

  - debug: var=status.stdout_lines
  - debug: var=status.stderr_lines


- name: HDFS management
  hosts: namenode[0]
  become_user: hdfs
  become: true
  tags: hdfs

  vars:
    home: /opt/hdfs/default

  tasks:
  - name: "{{op}} HDFS"
    shell: "{{home}}/sbin/{{op}}-dfs.sh"
    register: status

  - debug: var=status.stdout_lines
  - debug: var=status.stderr_lines


- name: Clean up
  hosts: hdfs
  become_user: hdfs
  become: true
  tags: logs

  vars:
    data: /var/hdfs/data

  tasks:
  - shell: "rm -rf {{data}}/logs/*"
    when: (op == 'clean')

