---
- name: Change iptables

  vars:
    protocol: "{{ proto | default('tcp') }}"

  hosts: "{{ host }}"
  become: true

  tasks:
    - name: "Open {{protocol}} on port {{port}}"
      shell: "iptables -A INPUT -p {{ protocol }} -m state --state NEW -m {{ protocol }} --dport {{ port }} -j ACCEPT"
      when: ((op is defined) and (op | trim == 'add') and not(protocol | trim == '') and (port is defined))

    - name: "Delete {{ protocol }} on port {{ port }}"
      shell: "iptables -D INPUT -p {{ protocol }} -m state --state NEW -m {{ protocol }} --dport {{ port }} -j ACCEPT"
      when: ((op is defined) and (op | trim == 'del') and not(protocol | trim == '') and (port is defined))
