---
- name: Re-config Zookeeper
  vars:
    user: root
    dest: /etc/zookeeper
    src: "/home/ansible@cloud.local/ansible/zookeeper"

  hosts: zookeeper
  become_user: "{{ user }}"
  become: true

  tasks:
    - name: Upload config files
      copy: src={{ item }} dest="{{ dest }}/conf" owner="{{ user }}" mode=644
      with_fileglob:
        - "{{ src }}/*"
